# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/nes.xdc

# IP: ip/vga_clk_wiz/vga_clk_wiz.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vga_clk_wiz || ORIG_REF_NAME==vga_clk_wiz} -quiet] -quiet

# IP: ip/chr_rom_1/chr_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chr_rom || ORIG_REF_NAME==chr_rom} -quiet] -quiet

# IP: ip/pgr_rom/pgr_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pgr_rom || ORIG_REF_NAME==pgr_rom} -quiet] -quiet
