# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Mark/Documents/NESV/NESV/nes.runs/synth_1/nes.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 5
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Mark/Documents/NESV/NESV/nes.cache/wt [current_project]
set_property parent.project_path C:/Users/Mark/Documents/NESV/NESV/nes.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/Mark/Documents/uiuc/ece385/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/Mark/Documents/NESV/NESV/nes.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/Mark/Documents/NESV/NESV/code/gen_nes/nestest.coe
add_files C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/imports/Downloads/microcode.coe
add_files C:/Users/Mark/Documents/NESV/NESV/code/gen_nes/01.basics.coe
add_files C:/Users/Mark/Documents/NESV/NESV/code/gen_nes/colors.coe
add_files C:/Users/Mark/Documents/NESV/NESV/code/gen_nes/chr_rom.coe
add_files C:/Users/Mark/Documents/NESV/NESV/code/gen_nes/prg_rom.coe
add_files C:/Users/Mark/Documents/NESV/NESV/code/gen_nes/prg_rom_dk.coe
add_files C:/Users/Mark/Documents/NESV/NESV/code/gen_nes/chr_rom_dk.coe
read_verilog -library xil_defaultlib -sv {
  C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/imports/src/VGA_controller.sv
  C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/new/chr_rom_mod.sv
  C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/new/clock.sv
  C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/new/controller.sv
  C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/new/cpu.sv
  C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/new/palletes.sv
  C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/new/pgr_rom.sv
  C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/new/ppu_to_hdmi.sv
  C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/new/ppu_v2.sv
  C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/new/nes.sv
}
read_vhdl -library xil_defaultlib {
  C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/imports/T_65_src/T65_Pack.vhd
  C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/imports/mister_core/T65_Pack.vhd
  C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/imports/T_65_src/T65_MCode.vhd
  C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/imports/T_65_src/T65_ALU.vhd
  C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/imports/T_65_src/T65.vhd
}
read_ip -quiet C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/ip/pgr_rom/pgr_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/nes.gen/sources_1/ip/pgr_rom/pgr_rom_ooc.xdc]

add_files C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/bd/mb_block/mb_block.bd
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_0_1/mb_block_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_0_1/mb_block_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_0_1/mb_block_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_dlmb_v10_0_1/mb_block_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_ilmb_v10_0_1/mb_block_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_dlmb_bram_if_cntlr_0_1/mb_block_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_ilmb_bram_if_cntlr_0_1/mb_block_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_lmb_bram_0_1/mb_block_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_xbar_0_1/mb_block_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_axi_intc_0_1/mb_block_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_axi_intc_0_1/mb_block_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_axi_intc_0_1/mb_block_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_mdm_1_0_1/mb_block_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_mdm_1_0_1/mb_block_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_1_0_1/mb_block_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_1_0_1/mb_block_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_1_0_1/mb_block_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_rst_clk_wiz_1_100M_0_1/mb_block_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_rst_clk_wiz_1_100M_0_1/mb_block_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_rst_clk_wiz_1_100M_0_1/mb_block_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_uartlite_0_0_1/mb_block_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_uartlite_0_0_1/mb_block_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_uartlite_0_0_1/mb_block_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_1/mb_block_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_1/mb_block_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_1/mb_block_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_2/mb_block_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_2/mb_block_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_2/mb_block_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_3/mb_block_axi_gpio_0_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_3/mb_block_axi_gpio_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_3/mb_block_axi_gpio_0_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_timer_0_0/mb_block_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_timer_0_0/mb_block_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/mb_block_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/mb_block_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/mb_block_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/mb_block_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/mb_block_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/6_2.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_0_1/data/mb_bootloop_le.elf]

read_ip -quiet C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/ip/chr_rom_1/chr_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/nes.gen/sources_1/ip/chr_rom_1/chr_rom_ooc.xdc]

read_ip -quiet C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/ip/vga_clk_wiz/vga_clk_wiz.xci
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/nes.gen/sources_1/ip/vga_clk_wiz/vga_clk_wiz_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/nes.gen/sources_1/ip/vga_clk_wiz/vga_clk_wiz.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/nes.gen/sources_1/ip/vga_clk_wiz/vga_clk_wiz_late.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/nes.gen/sources_1/ip/vga_clk_wiz/vga_clk_wiz_ooc.xdc]

read_ip -quiet C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/ip/hdmi_tx_0_1/hdmi_tx_0.xci

read_ip -quiet C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/ip/frame_buffr_1/frame_buffr.xci
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/nes.gen/sources_1/ip/frame_buffr_1/frame_buffr_ooc.xdc]

read_ip -quiet C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/nes.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/nes.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/nes.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_late.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/nes.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/nes.gen/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/nes.gen/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/nes.gen/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

read_ip -quiet C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/ip/cpu_ram/cpu_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/nes.gen/sources_1/ip/cpu_ram/cpu_ram_ooc.xdc]

read_ip -quiet C:/Users/Mark/Documents/NESV/NESV/nes.srcs/sources_1/ip/vram/vram.xci
set_property used_in_implementation false [get_files -all c:/Users/Mark/Documents/NESV/NESV/nes.gen/sources_1/ip/vram/vram_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Mark/Documents/NESV/NESV/nes.srcs/constrs_1/new/nes.xdc
set_property used_in_implementation false [get_files C:/Users/Mark/Documents/NESV/NESV/nes.srcs/constrs_1/new/nes.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/Mark/Documents/NESV/NESV/nes.srcs/utils_1/imports/synth_1/cpu_2A03.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top nes -part xc7s50csga324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef nes.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file nes_utilization_synth.rpt -pb nes_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
