# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/drew/uiuc/ece385/nes/nes.srcs/sources_1/ip/cpu_ram/cpu_ram.xci
# IP: The module: 'cpu_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/drew/uiuc/ece385/nes/nes.gen/sources_1/ip/cpu_ram/cpu_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/drew/uiuc/ece385/nes/nes.srcs/sources_1/ip/cpu_ram/cpu_ram.xci
# IP: The module: 'cpu_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/drew/uiuc/ece385/nes/nes.gen/sources_1/ip/cpu_ram/cpu_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
