# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/drew/ece385/nes/nes.srcs/sources_1/ip/frame_buffr_1/frame_buffr.xci
# IP: The module: 'frame_buffr' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/drew/ece385/nes/nes.gen/sources_1/ip/frame_buffr_1/frame_buffr_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_buffr'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/drew/ece385/nes/nes.srcs/sources_1/ip/frame_buffr_1/frame_buffr.xci
# IP: The module: 'frame_buffr' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/drew/ece385/nes/nes.gen/sources_1/ip/frame_buffr_1/frame_buffr_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_buffr'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
